dbt_trino_project:
  target: dev
  outputs:
    dev:
      type: trino
      host: trino-coordinator
      port: 8443
      user: data_engineer
      password: engineer123
      method: ldap          # ← ĐỔI từ none → ldap
      http_scheme: https
      catalog: iceberg
      schema: silver
      threads: 4

    staging:
      type: trino
      host: trino-coordinator
      port: 8443
      user: data_engineer
      password: engineer123
      method: ldap
      http_scheme: https
      catalog: iceberg
      schema: bronze
      threads: 4

    intermediate:
      type: trino
      host: trino-coordinator
      port: 8443
      user: data_engineer
      password: engineer123
      method: ldap
      http_scheme: https
      catalog: iceberg
      schema: silver
      threads: 4

    marts:
      type: trino
      host: trino-coordinator
      port: 8443
      user: data_engineer
      password: engineer123
      method: ldap
      http_scheme: https
      catalog: iceberg
      schema: gold
      threads: 4