import random
from faker import Faker
import pandas as pd
from datetime import datetime, timedelta, date
from io import BytesIO
import boto3

# ========== CONFIG MINIO ==========

MINIO_ENDPOINT = "http://localhost:9000"   # Sử dụng MinIO địa chỉ nội bộ
MINIO_ACCESS_KEY = "minio"
MINIO_SECRET_KEY = "minio123"
BUCKET = "lakehouse"

# Nơi mình đang để data daily
TARGET_PREFIX = "bronze/adventureworks/Sales/Faker_SalesOrderHeader_daily"

fake = Faker()

def get_s3_client():
    return boto3.client(
        "s3",
        endpoint_url=MINIO_ENDPOINT,
        aws_access_key_id=MINIO_ACCESS_KEY,
        aws_secret_access_key=MINIO_SECRET_KEY,
    )

def generate_fake_sales_for_date(target_date: date, n_rows: int = 50) -> pd.DataFrame:
    """
    Sinh thêm n_rows đơn hàng fake cho đúng 1 ngày (orderdate = target_date).
    Các giá trị như `totaldue` và `status` sẽ được làm biến động để dữ liệu không quá chính xác.
    """
    rows = []

    for _ in range(n_rows):
        orderdate = datetime.combine(target_date, datetime.min.time())
        
        # Faker orderdate với sự biến động nhỏ
        orderdate = orderdate + timedelta(days=random.randint(-2, 2))  # Làm thay đổi chút ít

        duedate = orderdate + timedelta(days=random.randint(3, 10))
        shipdate = orderdate + timedelta(days=random.randint(1, 7))

        subtotal = round(random.uniform(50, 500), 2)
        taxamt = round(subtotal * random.uniform(0.05, 0.15), 2)
        freight = round(random.uniform(5, 30), 2)
        
        # Faker totaldue có sự biến động
        totaldue = round(subtotal + taxamt + freight, 2) + random.uniform(-10, 10)  # Thêm vào một chút nhiễu

        row = {
            # Faker salesorderid, revisionnumber sẽ giữ nguyên
            "salesorderid": fake.random_int(min=600000, max=999999),
            "revisionnumber": 1,
            "orderdate": orderdate,
            "duedate": duedate,
            "shipdate": shipdate,
            "status": random.choice([1, 2, 3, 4, 99]),  # Faker giá trị status có thể sai
            "onlineorderflag": True,
            "salesordernumber": f"FAKE-{fake.random_int(100000, 999999)}",
            "purchaseordernumber": fake.bothify("PO########"),
            "accountnumber": fake.bothify("10-40#####"),
            "customerid": random.randint(11000, 40000),
            "salespersonid": float(random.randint(280, 300)),
            "territoryid": random.randint(1, 10),
            "billtoaddressid": random.randint(10000, 30000),
            "shiptoaddressid": random.randint(10000, 30000),
            "shipmethodid": random.randint(1, 5),
            "creditcardid": float(random.randint(1000, 2000)),
            "creditcardapprovalcode": fake.bothify("APPROVED-######"),
            "currencyrateid": float(random.randint(1, 10)),
            "subtotal": subtotal,
            "taxamt": taxamt,
            "freight": freight,
            "totaldue": totaldue,
            "comment": "fake order generated by Faker",
            "rowguid": fake.uuid4(),
            "modifieddate": datetime.utcnow(),
        }

        rows.append(row)

    df = pd.DataFrame(rows)
    return df

def upload_fake_daily_to_minio(run_date_str: str, n_rows: int = 50):
    """
    Sinh thêm n_rows đơn hàng cho ngày đó và upload vào MinIO
    """
    run_date = datetime.strptime(run_date_str, "%Y-%m-%d").date()

    df_fake = generate_fake_sales_for_date(run_date, n_rows=n_rows)

    s3 = get_s3_client()

    # Path trên MinIO: .../load_date=YYYY-MM-DD/salesorderheader_fake_YYYY-MM-DD.parquet
    key_prefix = f"{TARGET_PREFIX}/load_date={run_date}"
    key = f"{key_prefix}/salesorderheader_{run_date}.parquet"

    buffer = BytesIO()
    df_fake.to_parquet(buffer, index=False)
    buffer.seek(0)

    print(f"[UPLOAD FAKE] {run_date}: {len(df_fake)} dòng -> s3://{BUCKET}/{key}")
    s3.upload_fileobj(buffer, BUCKET, key)

    print("[DONE] Đã sinh & upload fake orders.")

if __name__ == "__main__":
    # Test nhanh: Sinh 10 đơn hàng cho ngày hôm nay
    today_str = date.today().strftime("%Y-%m-%d")
    upload_fake_daily_to_minio(today_str, n_rows=10)
